DROP TABLE IF EXISTS `CORE_FLOW_CONTEXT`;
CREATE TABLE `CORE_FLOW_CONTEXT` (
  `ID_FLOW_CONTEXT` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '交易上下文自增主键',
  `WORKFLOW_NAME` varchar(128) DEFAULT NULL COMMENT '工作流名称',
  `FLOW_STATUS` varchar(20) DEFAULT NULL,
  `REQ_TIME` timestamp NULL DEFAULT NULL COMMENT '交易请求时间',
  `RSP_TIME` timestamp NULL DEFAULT NULL COMMENT '交易响应时间',
  `CURRENT_WORK` varchar(40) DEFAULT NULL COMMENT '当前工作状态',
  `PROCESS_RESULT` varchar(20) DEFAULT NULL COMMENT '处理结果',
  PRIMARY KEY (`ID_FLOW_CONTEXT`)
) ENGINE=InnoDB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8mb4 COMMENT='工作流上下文';