DROP TABLE IF EXISTS `FWD_DETAIL`;
CREATE TABLE `FWD_DETAIL` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `REGID` bigint(20) DEFAULT NULL COMMENT '所属的转发登记记录ID',
  `FORWARD_TIME` timestamp NULL DEFAULT NULL COMMENT '转发时间',
  `FORWARD_FLAG` varchar(1) DEFAULT NULL COMMENT '调用失败F 成功S',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `LAST_UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=506914437960234499 DEFAULT CHARSET=utf8mb4 COMMENT='存储转发动作明细表';

DROP TABLE IF EXISTS `FWD_REGISTER`;
CREATE TABLE `FWD_REGISTER` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增序列主键',
  `REGISTER_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `REFERENCE` bigint(20) NOT NULL DEFAULT '0' COMMENT '流水号',
  `WORK_ID` varchar(40) NOT NULL DEFAULT '' COMMENT '机器ID',
  `NEXT_ACTIVE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下次激活时间',
  `FWD_TYPE` varchar(2) NOT NULL DEFAULT '' COMMENT '类型（全局/局部）0:全局 1：局部',
  `RETRY_COUNT` int(11) NOT NULL DEFAULT '0' COMMENT '重试次数',
  `RETRY_LIMIT` int(11) NOT NULL DEFAULT '0' COMMENT '重试次数上限',
  `BASE_INTERVAL` bigint(20) NOT NULL DEFAULT '0' COMMENT '基本时间间隔，单位毫秒',
  `INTERVAL_DELTA` bigint(20) NOT NULL DEFAULT '0' COMMENT '间隔时间增量，单位毫秒',
  `FWD_STATUS` varchar(2) NOT NULL DEFAULT '' COMMENT '状态 等待W，转发中D，注销C，转发次数达上限U',
  `BIZ_TYPE` varchar(5) NOT NULL DEFAULT '' COMMENT '业务类型',
  `CALL_CLASS` varchar(200) NOT NULL DEFAULT '' COMMENT '回调CLASS',
  `CALL_METHOD` varchar(200) NOT NULL DEFAULT '' COMMENT '回调方法',
  `DATA_CENTER_ID` varchar(10) NOT NULL DEFAULT '' COMMENT '机组ID',
  `CREATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `LAST_UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  `EXT1` varchar(100) NOT NULL DEFAULT '' COMMENT '备用1',
  `EXT2` varchar(100) NOT NULL DEFAULT '' COMMENT '备用2',
  `EXT3` varchar(100) NOT NULL DEFAULT '' COMMENT '备用3',
  `EXT4` varchar(100) NOT NULL DEFAULT '' COMMENT '备用4',
  `EXT5` varchar(100) NOT NULL DEFAULT '' COMMENT '备用5',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=720732 DEFAULT CHARSET=utf8mb4 COMMENT='存储转发登记表';

DROP TABLE IF EXISTS `TTO_INF`;
CREATE TABLE `TTO_INF` (
  `TTOID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增序列主键',
  `REFERENCE` bigint(20) DEFAULT NULL COMMENT '流水号',
  `REGISTER_TIME` timestamp NULL DEFAULT NULL COMMENT '注册时间',
  `TTO_TYPE` varchar(2) DEFAULT NULL COMMENT '类型（全局/局部）0:全局 1：局部',
  `TTO_STATUS` varchar(1) DEFAULT NULL COMMENT 'STATUS状态 0：未执行 1：已执行',
  `BIZ_TYPE` varchar(5) DEFAULT NULL COMMENT '业务类型',
  `CALL_CLASS` varchar(200) DEFAULT NULL COMMENT '回调CLASS',
  `CALL_METHOD` varchar(200) DEFAULT NULL COMMENT '回调方法',
  `WORK_ID` varchar(40) DEFAULT NULL COMMENT '机器ID',
  `EXCUTE_TIME` timestamp NULL DEFAULT NULL COMMENT '执行时间',
  `EXPIRED_TIME` varchar(10) DEFAULT NULL,
  `DATA_CENTER_ID` varchar(10) DEFAULT NULL COMMENT '机组ID',
  `EXT1` varchar(100) DEFAULT NULL COMMENT '备用1',
  `EXT2` varchar(100) DEFAULT NULL COMMENT '备用2',
  `EXT3` varchar(100) DEFAULT NULL COMMENT '备用3',
  `EXT4` varchar(100) DEFAULT NULL COMMENT '备用4',
  `EXT5` varchar(100) DEFAULT NULL COMMENT '备用5',
  `CREATE_TIME` timestamp NULL DEFAULT NULL COMMENT '记录创建时间',
  `LAST_UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`TTOID`),
  KEY `IDX_TTO_EXCU_TIME` (`EXCUTE_TIME`)
) ENGINE=InnoDB AUTO_INCREMENT=193492 DEFAULT CHARSET=utf8mb4 COMMENT='超时控制处理表';